“Design principles”: Fix typos grammatical errors
wikimedia/WikimediaUI-Style-Guide pull request #463
Opened 2021-05-19 17:32 UTC by MoulinaPradhan

Found the following typos and grammatical errors on Design Principles and Design Principle  Accessibility page.

2021-05-19 18:25 UTC, Volker-E commented
Thanks for your contribution @MoulinaPradhan! We'll look into it shortly.

2021-05-28 19:41 UTC, MoulinaPradhan commented
I have made the changes according to the suggestions/comments

2021-06-14 17:33 UTC, Volker-E commented on design-principles_accessibility.html
> +						<p>Other categories like speech impairments don't apply in our graphical user-interface focus; while hearing and cognitive impairments are to be covered on a content level. See for example Simp
Duplication of “for example” doesn't make sense here.

2021-06-14 17:34 UTC, Volker-E requested changes
Everything else looks good, happy to merge with last request.

2021-06-14 18:03 UTC, MoulinaPradhan commented on design-principles_accessibility.html
> +						<p>Other categories like speech impairments don't apply in our graphical user-interface focus; while hearing and cognitive impairments are to be covered on a content level. See for example Simp
I have corrected it.

2021-06-14 18:05 UTC, Volker-E approved these changes

2021-06-14 18:08 UTC, merged

2021-06-14 18:08 UTC, Volker-E commented
Thanks @MoulinaPradhan and @grammarbot! :)