[WIP] Migrate from Grunt to npm for imagemin
wikimedia/WikimediaUI-Style-Guide pull request #479
Opened 2021-07-01 16:58 UTC by Ladsgroup

It's blocked on this upstream issue:
https://github.com/imagemin/imagemin/issues/191

Bug: T246321

2021-07-03 13:15 UTC, Volker-E commented on package.json
> +		"build": "grunt && imagemin img/**/*.png --plugin=zopfli --out-dir=img/ && imagemin resources/*.png --plugin=zopfli --out-dir=resources/",
Per directory seems fine-ish as long as imagemin doesn't provide a better option. We don't have that many directories to optimize on. 
One thing that got lost is the exclusion of components_overview.png above. It results in an erroneous SVG output.

2021-07-03 13:17 UTC, Volker-E commented
> It's blocked on this upstream issue:
> [imagemin/imagemin#191](https://github.com/imagemin/imagemin/issues/191)
> 
> Bug: T246321

Think it's fine to proceed with different imagemin calls per project.

2021-07-05 18:42 UTC, Ladsgroup commented on package.json
> +		"build": "grunt && imagemin img/**/*.png --plugin=zopfli --out-dir=img/ && imagemin resources/*.png --plugin=zopfli --out-dir=resources/",
Done

2021-07-05 18:42 UTC, Ladsgroup commented
> > It's blocked on this upstream issue:
> > [imagemin/imagemin#191](https://github.com/imagemin/imagemin/issues/191)
> > Bug: T246321
> 
> Think it's fine to proceed with different imagemin calls per project.

Done.

2021-07-06 12:49 UTC, Volker-E commented on package.json
> +		"build": "grunt && npx npm-run-all build:*",
Why the 'npx' command?

2021-07-06 12:50 UTC, Volker-E commented on package.json
> +		"build:imagemin": "imagemin img/components/*.png --plugin=zopfli --out-dir=img/components/ && imagemin img/design-principles/*.png --plugin=zopfli --out-dir=img/design-principles/ && imagemin img/v
What does `\\` stand for? First time seeing this.

2021-07-06 15:38 UTC, Ladsgroup commented on package.json
> +		"build": "grunt && npx npm-run-all build:*",
it failed without it, it seems after && it's needed.

2021-07-06 15:40 UTC, Ladsgroup commented on package.json
> +		"build:imagemin": "imagemin img/components/*.png --plugin=zopfli --out-dir=img/components/ && imagemin img/design-principles/*.png --plugin=zopfli --out-dir=img/design-principles/ && imagemin img/v
The first one is escaping the parentheses in json so bash takes it and the second one is the escaping of the first slash. otherwise running npm run build fails bad.

2021-07-07 15:05 UTC, Volker-E commented
In my testing, `npm run build:imagemin` currently isn't minifying the PNG images, even though it provides command line feedback. See these two test images, that should both land somewhere between 14 and max 30 kB
![design-style-guide_](https://user-images.githubusercontent.com/619536/124783356-da8f9d00-def9-11eb-933a-301c9f0d26d5.png)
![design-style-guide](https://user-images.githubusercontent.com/619536/124783368-dbc0ca00-def9-11eb-8a8d-a2b8e5a3bb17.png)

2021-08-03 18:27 UTC, Ladsgroup commented
> See comment on not correctly handled minification in main conversation thread with example images.

So I ran it to debug and it very much compresses the images but not as much as you want it to be, e.g. the the second one that it 118KB gets reduced to 63KB. There is the --more option I can try but I really can't force how small it will become.

2021-08-03 18:34 UTC, Ladsgroup commented
I added more iterations according to https://www.npmjs.com/package/imagemin-zopfli but not a big difference.

2021-08-07 20:10 UTC, Ladsgroup commented
Now trying with squoosh, let's see how that works

2021-08-07 20:25 UTC, Ladsgroup commented
It reduced the second picture to 64KB but that's the best oxipng can do it seems, did you try with jpg output?

2021-08-09 07:36 UTC, Volker-E commented
I guess that's because Google wanted to push their/newer image formats like WebP or [AVIF](https://caniuse.com/avif) and didn't put further optimizations into PNG. 
With WebP in the Squoosh online editor it gets down to 33 kB lossless and 13 kB with a very high-quality lossy compression. 

Apart from that Squoosh doesn't run locally. 

```
node_modules/@squoosh/cli/src/index.js:3
import { program } from 'commander/esm.mjs';
       ^

SyntaxError: Unexpected token {
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
```

2021-08-09 07:37 UTC, Volker-E requested changes
See inline comment about not being able to run script.

2021-08-09 07:38 UTC, Ladsgroup commented
> See inline comment about not being able to run script.

I had the same problem, you need to update your node version.

2021-08-09 07:48 UTC, Ladsgroup commented
The version in .nvm file is good enough.

2021-08-09 07:57 UTC, Volker-E commented
Ouch, I forgot that I've updated node here, while everything else Wikimedia for me is still on v10.15.2.

2021-08-09 08:02 UTC, Volker-E approved these changes

2021-08-09 08:02 UTC, Volker-E commented
With the working dependency now, all but three PNGs got compressed to larger output files. The difference is in a 1-20% range, with vast majority max 12% bigger than before with grunt-imagemin. That's tolerable in order to rely on a maintained project, with the gain switching over to a more modern tooling and opening up windows for up-to-date compression algorithms, that might generally outperform current PNG compression.

2021-08-09 08:05 UTC, merged

2021-08-09 08:09 UTC, Volker-E commented
Thanks @Ladsgroup for your continuous great work here. Appreciated!

2021-08-09 08:12 UTC, Ladsgroup commented
> Thanks @Ladsgroup for your continuous great work here. Appreciated!

Anytime <3